# Generated by Django 2.2.10 on 2021-11-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('TEXT', 'TEXT'), ('ONE_OPTION', 'ONE_OPTION'), ('PLURAL_OPTION', 'PLURAL_OPTION')], default='TEXT', max_length=30)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Survey')),
            ],
        ),
    ]
