# Generated by Django 2.2.10 on 2021-11-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
    ]
